#!/bin/bash

# 🚀 The IK11 Portfolio - Start Guide Script

echo "╔════════════════════════════════════════════════════╗"
echo "║     Welcome to The IK11 Portfolio Project!         ║"
echo "║     A Modern Flutter Web Portfolio                 ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Project Setup Instructions:${NC}"
echo ""
echo "1️⃣  Get dependencies:"
echo -e "   ${GREEN}flutter pub get${NC}"
echo ""
echo "2️⃣  Customize your portfolio:"
echo -e "   ${GREEN}Open: lib/core/constants/app_constants.dart${NC}"
echo "   - Update fullName, email, phone, social links"
echo "   - Update skills and services"
echo ""
echo "3️⃣  Update colors (optional):"
echo -e "   ${GREEN}Open: lib/core/theme/app_theme.dart${NC}"
echo "   - Change primary color and other colors"
echo ""
echo "4️⃣  Update section content:"
echo "   - Projects: lib/ui/sections/projects_section.dart"
echo "   - Experience: lib/ui/sections/experience_section.dart"
echo "   - Testimonials: lib/ui/sections/testimonials_section.dart"
echo "   - And other sections..."
echo ""
echo "5️⃣  Configure Firebase (optional):"
echo -e "   ${GREEN}Update: lib/configs/app_config.dart${NC}"
echo "   - Add your Firebase project ID and API key"
echo ""
echo "6️⃣  Run the app:"
echo -e "   ${GREEN}flutter run -d chrome${NC}"
echo ""
echo "7️⃣  Build for production:"
echo -e "   ${GREEN}flutter build web --release${NC}"
echo ""
echo "8️⃣  Deploy:"
echo "   - Netlify: netlify deploy --prod --dir build/web"
echo "   - Firebase: firebase deploy"
echo "   - GitHub Pages: git push origin gh-pages"
echo ""

echo -e "${BLUE}📚 Documentation Files:${NC}"
echo "   📖 README_PORTFOLIO.md    - Main documentation"
echo "   📖 SETUP_GUIDE.md         - Detailed setup guide"
echo "   📖 DOCUMENTATION.md       - Complete technical docs"
echo "   📖 QUICK_REFERENCE.md     - Quick reference"
echo "   📖 CHANGELOG.md           - Version history"
echo ""

echo -e "${BLUE}🎯 Key Files to Customize:${NC}"
echo "   1. lib/core/constants/app_constants.dart"
echo "   2. lib/core/theme/app_theme.dart"
echo "   3. lib/ui/sections/*.dart (all section files)"
echo "   4. lib/configs/app_config.dart (Firebase)"
echo ""

echo -e "${BLUE}🚀 Quick Commands:${NC}"
echo -e "   ${GREEN}flutter run -d chrome${NC}              # Run app"
echo -e "   ${GREEN}flutter build web --release${NC}        # Build for production"
echo -e "   ${GREEN}dart format .${NC}                       # Format code"
echo -e "   ${GREEN}flutter analyze${NC}                    # Analyze code"
echo ""

echo -e "${BLUE}🔗 Useful Resources:${NC}"
echo "   • Flutter Docs: https://flutter.dev/docs"
echo "   • Firebase Docs: https://firebase.google.com/docs"
echo "   • Material Design: https://material.io/design"
echo "   • Dart Docs: https://dart.dev/guides"
echo ""

echo -e "${YELLOW}✅ Project Structure:${NC}"
echo "   lib/"
echo "   ├── core/          - Theme, constants, utilities"
echo "   ├── data/          - Firebase service, models"
echo "   ├── ui/"
echo "   │   ├── pages/    - Main pages"
echo "   │   ├── sections/ - Portfolio sections"
echo "   │   └── widgets/  - Reusable widgets"
echo "   ├── configs/       - Configuration files"
echo "   └── main.dart      - Entry point"
echo ""

echo -e "${YELLOW}🎨 Color Palette:${NC}"
echo "   Primary:     #7C3AED (Purple)"
echo "   Background:  #0F172A (Dark)"
echo "   Secondary:   #1E293B (Darker)"
echo "   Accent1:     #06B6D4 (Cyan)"
echo "   Accent2:     #10B981 (Green)"
echo "   Accent3:     #F59E0B (Amber)"
echo "   Accent4:     #F87171 (Red)"
echo ""

echo -e "${YELLOW}📱 Responsive Breakpoints:${NC}"
echo "   Mobile:   < 768px"
echo "   Tablet:   768px - 1200px"
echo "   Desktop:  > 1200px"
echo ""

echo -e "${GREEN}🎉 You're all set! Happy coding! 🚀${NC}"
echo ""
echo "Questions? Check the documentation files!"
echo ""
